#!/usr/bin/env bash
set -e

source setup-git.sh

brew install nvm

brew install duti
duti -s com.sublimetext.3 public.plain-text all # use sublime text for text files

brew install postgresql
brew services start postgresql

brew install ruby-install
brew install chruby
ruby-install --latest ruby
source "$BASH_SCRIPTS_DIR/chruby.bash"
gem install bundler

brew install geckodriver # used to automate firefox
